#!/bin/bash
# 批量添加 Twitter 账号的辅助脚本

echo "=================================="
echo "批量添加 Twitter 账号"
echo "=================================="
echo ""
echo "需要添加的 21 个账号："
echo ""
echo "最高优先级（3个）："
echo "1. geoffreyhinton - Geoffrey Hinton（图灵奖得主）"
echo "2. Yoshua_Bengio - Yoshua Bengio（图灵奖得主）"
echo "3. aidangomez - Aidan Gomez（Cohere CEO）"
echo ""
echo "高优先级（5个）："
echo "4. gdb - Greg Brockman（OpenAI）"
echo "5. mustafasuleyman - Mustafa Suleyman（Microsoft AI）"
echo "6. NoamShazeer - Noam Shazeer（Character.AI）"
echo "7. jackclarkSF - Jack Clark（Anthropic）"
echo "8. drfeifei - Fei-Fei Li（Stanford）"
echo ""
echo "中等优先级（7个）："
echo "9. OriolVinyalsML - Oriol Vinyals"
echo "10. SebastienBubeck - Sebastien Bubeck"
echo "11. soumithchintala - Soumith Chintala"
echo "12. johnschulman2 - John Schulman"
echo "13. woj_zaremba - Wojciech Zaremba"
echo "14. _jasonwei - Jason Wei"
echo "15. pabbeel - Pieter Abbeel"
echo ""
echo "低优先级（6个）："
echo "16. EpochAIResearch - Epoch AI Research"
echo "17. rasbt - Sebastian Raschka"
echo "18. indigox - Indigo"
echo "19. zephyr_z9 - Zephyr"
echo "20. lennysan - Lenny"
echo "21. thinkymachines - Thinky Machines"
echo ""
echo "=================================="
echo "获取 User ID 的步骤："
echo "=================================="
echo ""
echo "1. 访问 https://tweeterid.com/"
echo "2. 输入用户名（如 geoffreyhinton）"
echo "3. 点击 'Convert'"
echo "4. 复制显示的数字 ID"
echo "5. 使用以下命令添加："
echo ""
echo "   ./scripts/add_account.sh <username> <user_id> \"<display_name>\""
echo ""
echo "示例："
echo "   ./scripts/add_account.sh geoffreyhinton 14498259 \"Geoffrey Hinton\""
echo ""
echo "=================================="
echo ""
echo "建议：先添加前 3 个最重要的账号"
echo ""
