#!/bin/bash
# 快速添加账号脚本

cd /Users/pingxn7/Desktop/x/backend

echo ""
echo "================================================================================"
echo "🚀 快速添加 Twitter 账号"
echo "================================================================================"
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 打开浏览器访问: https://tweeterid.com/"
echo "2. 输入账号名查询 user_id"
echo "3. 运行添加命令"
echo ""
echo "================================================================================"
echo "📝 需要添加的 21 个账号"
echo "================================================================================"
echo ""
echo "高优先级（建议先添加）："
echo "  1. geoffreyhinton - Geoffrey Hinton"
echo "  2. Yoshua_Bengio - Yoshua Bengio"
echo "  3. aidangomez - Aidan Gomez"
echo "  4. gdb - Greg Brockman"
echo "  5. NoamShazeer - Noam Shazeer"
echo ""
echo "中优先级："
echo "  6. johnschulman2 - John Schulman"
echo "  7. woj_zaremba - Wojciech Zaremba"
echo "  8. mustafasuleyman - Mustafa Suleyman"
echo "  9. pabbeel - Pieter Abbeel"
echo "  10. OriolVinyalsML - Oriol Vinyals"
echo "  11. SebastienBubeck - Sebastien Bubeck"
echo "  12. soumithchintala - Soumith Chintala"
echo "  13. rasbt - Sebastian Raschka"
echo ""
echo "低优先级："
echo "  14. EpochAIResearch"
echo "  15. drfeifei - Fei-Fei Li"
echo "  16. indigox"
echo "  17. jackclarkSF - Jack Clark"
echo "  18. zephyr_z9"
echo "  19. _jasonwei - Jason Wei"
echo "  20. lennysan"
echo "  21. thinkymachines"
echo ""
echo "================================================================================"
echo "⚡ 添加命令格式"
echo "================================================================================"
echo ""
echo "  ./scripts/add_one.sh username user_id \"Display Name\""
echo ""
echo "示例："
echo "  ./scripts/add_one.sh geoffreyhinton 123456789 \"Geoffrey Hinton\""
echo ""
echo "================================================================================"
echo ""
echo "准备好了吗？"
echo ""
echo "选项 A: 运行交互式脚本（推荐）"
echo "  source venv/bin/activate"
echo "  python scripts/manual_add_interactive.py"
echo ""
echo "选项 B: 手动逐个添加"
echo "  在 tweeterid.com 查询后使用 add_one.sh 添加"
echo ""
echo "================================================================================"
echo ""
