#!/bin/bash
# 一键查看添加账号的所有工具和文档

echo ""
echo "================================================================================"
echo "Twitter 账号添加工具 - 完整列表"
echo "================================================================================"
echo ""

echo "📚 文档和指南:"
echo "--------------------------------------------------------------------------------"
echo "  1. scripts/README_ADD_ACCOUNTS.md          - 快速参考（推荐先看这个）"
echo "  2. scripts/QUICK_START_ADD_ACCOUNTS.md     - 完整快速开始指南"
echo "  3. scripts/HOW_TO_ADD_ACCOUNTS.md          - 详细说明文档"
echo ""

echo "🛠️  添加工具:"
echo "--------------------------------------------------------------------------------"
echo "  1. scripts/import_user_ids.py              - 批量导入脚本（推荐）"
echo "  2. scripts/add_accounts_interactive.py     - 交互式添加工具"
echo "  3. scripts/quick_import.sh                 - 快速导入脚本（带确认）"
echo ""

echo "📝 数据文件:"
echo "--------------------------------------------------------------------------------"
echo "  1. scripts/usernames_to_add.txt            - 需要添加的 username 列表"
echo "  2. scripts/user_ids_to_import.txt          - 导入文件（需要你编辑）"
echo ""

echo "✅ 验证工具:"
echo "--------------------------------------------------------------------------------"
echo "  1. scripts/check_status.py                 - 查看系统状态"
echo "  2. scripts/manual_collect.py               - 手动收集推文"
echo ""

echo "================================================================================"
echo ""
echo "🚀 快速开始（3 步完成）:"
echo ""
echo "步骤 1: 获取 User IDs"
echo "  访问: https://tweeterid.com/"
echo "  逐个输入 username，获取 user_id"
echo ""
echo "步骤 2: 编辑导入文件"
echo "  nano scripts/user_ids_to_import.txt"
echo "  格式: username user_id"
echo ""
echo "步骤 3: 运行导入"
echo "  ./venv/bin/python scripts/import_user_ids.py"
echo ""
echo "================================================================================"
echo ""
echo "📋 需要添加的 28 个账号:"
echo ""
cat scripts/usernames_to_add.txt
echo ""
echo "================================================================================"
echo ""
echo "💡 推荐工作流程:"
echo ""
echo "  1. 打开 https://tweeterid.com/"
echo "  2. 打开 scripts/user_ids_to_import.txt"
echo "  3. 逐个查询并记录（格式: username user_id）"
echo "  4. 运行: ./venv/bin/python scripts/import_user_ids.py"
echo "  5. 验证: python scripts/check_status.py"
echo ""
echo "================================================================================"
echo ""
echo "📖 查看完整文档:"
echo "  cat scripts/README_ADD_ACCOUNTS.md"
echo ""
echo "🆘 需要帮助?"
echo "  cat scripts/QUICK_START_ADD_ACCOUNTS.md"
echo ""
echo "================================================================================"
echo ""
