"""
Email service - Send daily digest emails using Resend.
"""
from typing import Optional
from datetime import datetime
from loguru import logger
import resend

from app.config import settings
from app.models.daily_summary import DailySummary
from app.models.processed_tweet import ProcessedTweet


class EmailService:
    """Service to send email notifications."""

    def __init__(self):
        if settings.resend_api_key:
            resend.api_key = settings.resend_api_key

    def format_email_body(
        self,
        summary: DailySummary,
        highlights: list[ProcessedTweet],
        summary_url: str
    ) -> str:
        """
        Format email body with highlights summary and top tweets.

        Args:
            summary: DailySummary object
            highlights: List of top ProcessedTweet objects
            summary_url: URL to full summary page

        Returns:
            HTML email body
        """
        # Format date
        date_str = summary.date.strftime("%Y年%m月%d日")

        # Build highlights list
        highlights_html = ""
        for i, tweet in enumerate(highlights[:10], 1):
            engagement = (
                f"👍 {self._format_number(tweet.tweet.like_count)} "
                f"🔄 {self._format_number(tweet.tweet.retweet_count)} "
                f"💬 {self._format_number(tweet.tweet.reply_count)}"
            )
            highlights_html += f"""
            <li style="margin-bottom: 12px;">
                <strong>@{tweet.tweet.account.username}</strong> - {tweet.summary or tweet.tweet.text[:100]}
                <br>
                <span style="color: #666; font-size: 14px;">{engagement}</span>
            </li>
            """

        # Build email HTML
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
                <h1 style="margin: 0; font-size: 28px;">🤖 AI News Digest</h1>
                <p style="margin: 10px 0 0 0; font-size: 16px; opacity: 0.9;">{date_str}</p>
            </div>

            <div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px;">
                <div style="background: white; padding: 25px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #667eea;">
                    <h2 style="margin-top: 0; color: #667eea; font-size: 20px;">📌 今日关键亮点</h2>
                    <div style="color: #555; line-height: 1.8;">
                        {summary.highlights_summary or "今日AI领域有多项重要进展。"}
                    </div>
                </div>

                <div style="background: white; padding: 25px; border-radius: 8px; margin-bottom: 20px;">
                    <h2 style="margin-top: 0; color: #333; font-size: 18px;">🔥 今日精选 (Top {len(highlights)})</h2>
                    <ol style="padding-left: 20px; margin: 15px 0;">
                        {highlights_html}
                    </ol>
                    {f'<p style="color: #666; font-size: 14px; margin-top: 20px;">另有 {summary.other_tweets_count} 条AI资讯，点击下方查看完整列表。</p>' if summary.other_tweets_count > 0 else ''}
                </div>

                <div style="text-align: center; margin-top: 30px;">
                    <a href="{summary_url}" style="display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 15px 40px; text-decoration: none; border-radius: 25px; font-weight: bold; font-size: 16px;">
                        查看完整汇总 →
                    </a>
                </div>

                <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #999; font-size: 12px;">
                    <p>共收集 {summary.tweet_count} 条AI相关推文 | 精选 {summary.top_tweets_count} 条</p>
                    <p style="margin-top: 10px;">
                        Generated by AI News Collector
                    </p>
                </div>
            </div>
        </body>
        </html>
        """

        return html

    def _format_number(self, num: int) -> str:
        """Format large numbers with K/M suffix."""
        if num >= 1000000:
            return f"{num / 1000000:.1f}M"
        if num >= 1000:
            return f"{num / 1000:.1f}K"
        return str(num)

    async def send_daily_digest(
        self,
        summary: DailySummary,
        highlights: list[ProcessedTweet],
        recipient: Optional[str] = None
    ) -> bool:
        """
        Send daily digest email.

        Args:
            summary: DailySummary object
            highlights: List of top ProcessedTweet objects
            recipient: Email recipient (defaults to settings.email_to)

        Returns:
            True if sent successfully, False otherwise
        """
        if not settings.enable_email or not settings.resend_api_key:
            logger.info("Email sending disabled or not configured")
            return False

        recipient = recipient or settings.email_to
        date_str = summary.date.strftime("%Y-%m-%d")

        # Build summary URL
        summary_url = f"{settings.frontend_url}/summary/{summary.url_slug}"

        # Format email body
        html_body = self.format_email_body(summary, highlights, summary_url)

        try:
            # Send email via Resend
            params = {
                "from": settings.email_from,
                "to": [recipient],
                "subject": f"AI News Digest - {date_str} | 今日精选{len(highlights)}条",
                "html": html_body
            }

            response = resend.Emails.send(params)
            logger.info(f"Email sent successfully to {recipient}: {response}")
            return True

        except Exception as e:
            logger.error(f"Error sending email: {e}")
            return False


# Global email service instance
email_service = EmailService()
