"""Mako template for migration scripts."""
"""Initial migration

Revision ID: 648ebc023000
Revises: 
Create Date: 2026-02-07 08:24:08.004064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648ebc023000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('url_slug', sa.String(length=100), nullable=False),
    sa.Column('tweet_count', sa.Integer(), nullable=False),
    sa.Column('top_tweets_count', sa.Integer(), nullable=False),
    sa.Column('other_tweets_count', sa.Integer(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('highlights_summary', sa.Text(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_recipient', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summaries_date'), 'daily_summaries', ['date'], unique=True)
    op.create_index(op.f('ix_daily_summaries_url_slug'), 'daily_summaries', ['url_slug'], unique=True)
    op.create_table('monitored_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_tweet_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_accounts_is_active'), 'monitored_accounts', ['is_active'], unique=False)
    op.create_index(op.f('ix_monitored_accounts_user_id'), 'monitored_accounts', ['user_id'], unique=True)
    op.create_index(op.f('ix_monitored_accounts_username'), 'monitored_accounts', ['username'], unique=False)
    op.create_table('tweets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tweet_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tweet_url', sa.String(length=500), nullable=False),
    sa.Column('tweet_metadata', sa.JSON(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('retweet_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('bookmark_count', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['monitored_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweets_created_at'), 'tweets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tweets_engagement_score'), 'tweets', ['engagement_score'], unique=False)
    op.create_index(op.f('ix_tweets_processed'), 'tweets', ['processed'], unique=False)
    op.create_index(op.f('ix_tweets_tweet_id'), 'tweets', ['tweet_id'], unique=True)
    op.create_index(op.f('ix_tweets_user_id'), 'tweets', ['user_id'], unique=False)
    op.create_table('processed_tweets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tweet_id', sa.BigInteger(), nullable=False),
    sa.Column('is_ai_related', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('screenshot_generated_at', sa.DateTime(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_tweets_importance_score'), 'processed_tweets', ['importance_score'], unique=False)
    op.create_index(op.f('ix_processed_tweets_is_ai_related'), 'processed_tweets', ['is_ai_related'], unique=False)
    op.create_index(op.f('ix_processed_tweets_processed_at'), 'processed_tweets', ['processed_at'], unique=False)
    op.create_index(op.f('ix_processed_tweets_tweet_id'), 'processed_tweets', ['tweet_id'], unique=True)
    op.create_table('summary_tweets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.BigInteger(), nullable=False),
    sa.Column('processed_tweet_id', sa.BigInteger(), nullable=False),
    sa.Column('display_type', sa.Enum('HIGHLIGHT', 'SUMMARY', name='displaytype'), nullable=False),
    sa.Column('rank_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['processed_tweet_id'], ['processed_tweets.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['daily_summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_tweets_display_type'), 'summary_tweets', ['display_type'], unique=False)
    op.create_index(op.f('ix_summary_tweets_processed_tweet_id'), 'summary_tweets', ['processed_tweet_id'], unique=False)
    op.create_index(op.f('ix_summary_tweets_summary_id'), 'summary_tweets', ['summary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_tweets_summary_id'), table_name='summary_tweets')
    op.drop_index(op.f('ix_summary_tweets_processed_tweet_id'), table_name='summary_tweets')
    op.drop_index(op.f('ix_summary_tweets_display_type'), table_name='summary_tweets')
    op.drop_table('summary_tweets')
    op.drop_index(op.f('ix_processed_tweets_tweet_id'), table_name='processed_tweets')
    op.drop_index(op.f('ix_processed_tweets_processed_at'), table_name='processed_tweets')
    op.drop_index(op.f('ix_processed_tweets_is_ai_related'), table_name='processed_tweets')
    op.drop_index(op.f('ix_processed_tweets_importance_score'), table_name='processed_tweets')
    op.drop_table('processed_tweets')
    op.drop_index(op.f('ix_tweets_user_id'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_tweet_id'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_processed'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_engagement_score'), table_name='tweets')
    op.drop_index(op.f('ix_tweets_created_at'), table_name='tweets')
    op.drop_table('tweets')
    op.drop_index(op.f('ix_monitored_accounts_username'), table_name='monitored_accounts')
    op.drop_index(op.f('ix_monitored_accounts_user_id'), table_name='monitored_accounts')
    op.drop_index(op.f('ix_monitored_accounts_is_active'), table_name='monitored_accounts')
    op.drop_table('monitored_accounts')
    op.drop_index(op.f('ix_daily_summaries_url_slug'), table_name='daily_summaries')
    op.drop_index(op.f('ix_daily_summaries_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
